# -*- coding: utf-8 -*-
"""main.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1sfDfNOFoshsiiBe-0eaiuSYGxEi9XZ77
"""

from fastapi import FastAPI
from pydantic import BaseModel
import joblib

app = FastAPI()

# Load trained model
model = joblib.load("/content/model.pkl")

class IrisInput(BaseModel):
    sepal_length: float
    sepal_width: float
    petal_length: float
    petal_width: float

@app.get("/")
def home():
    return {"message": "Iris Prediction API is running"}

@app.post("/predict")
def predict(iris: IrisInput):
  feature = [[iris.sepal_length, iris.sepal_width, iris.petal_length, iris.petal_width]]
  prediction = model.predict(feature)
  classes={0:'setosa',1:'versicolor',2:'virginica'}
  return {
        "prediction": int(prediction),
        "class": classes[prediction]
    }